In [2]:
from sklearn.datasets import make_moons
import pandas as pd
import numpy as np

import torch
from torch.autograd import Variable
import torch.nn as nn
from torch.utils.data import Dataset, DataLoader
import torch.nn.functional as F

def to_categorical(y, num_classes):
    """1-hot encodes a tensor"""
    return np.eye(num_classes, dtype='uint8')[y]

X, y = make_moons(n_samples=1000, noise=.1)
y = to_categorical(y, 2)

In [7]:
class PrepareData(Dataset):

    def __init__(self, X, y):
        if not torch.is_tensor(X):
            self.X = torch.from_numpy(X)
        if not torch.is_tensor(y):
            self.y = torch.from_numpy(y)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

ds = PrepareData(X=X, y=y)


In [6]:
ds = DataLoader(ds, batch_size=50, shuffle=True)

In [18]:
ds.X.shape

torch.Size([1000, 2])

In [15]:
for i, (x,y) in enumerate(ds):
    print(x)

tensor([2.0071, 0.6378], dtype=torch.float64)
tensor([ 0.3032, -0.4039], dtype=torch.float64)
tensor([-1.0787,  0.4671], dtype=torch.float64)
tensor([-0.4528,  0.7828], dtype=torch.float64)
tensor([0.0729, 1.0115], dtype=torch.float64)
tensor([ 0.3762, -0.5481], dtype=torch.float64)
tensor([ 0.5283, -0.5016], dtype=torch.float64)
tensor([-0.1861,  0.9851], dtype=torch.float64)
tensor([-1.0152,  0.1408], dtype=torch.float64)
tensor([ 0.4122, -0.2463], dtype=torch.float64)
tensor([-0.9174,  0.3219], dtype=torch.float64)
tensor([0.2573, 0.0279], dtype=torch.float64)
tensor([ 0.3768, -0.3763], dtype=torch.float64)
tensor([ 1.6121, -0.2965], dtype=torch.float64)
tensor([0.7915, 0.2671], dtype=torch.float64)
tensor([ 0.6716, -0.4827], dtype=torch.float64)
tensor([ 1.1452, -0.4524], dtype=torch.float64)
tensor([1.8492, 0.5295], dtype=torch.float64)
tensor([2.1897, 0.4616], dtype=torch.float64)
tensor([1.0012, 0.2881], dtype=torch.float64)
tensor([-0.7258,  0.5479], dtype=torch.float64)
tensor

tensor([0.0563, 1.2191], dtype=torch.float64)
tensor([-0.6002,  1.0073], dtype=torch.float64)
tensor([ 0.9709, -0.3484], dtype=torch.float64)
tensor([-0.2308,  0.9449], dtype=torch.float64)
tensor([0.1614, 0.9856], dtype=torch.float64)
tensor([ 1.7237, -0.0780], dtype=torch.float64)
tensor([0.1670, 0.5149], dtype=torch.float64)
tensor([ 1.9322, -0.0497], dtype=torch.float64)
tensor([0.0550, 0.2354], dtype=torch.float64)
tensor([ 0.5768, -0.6757], dtype=torch.float64)
tensor([ 1.7653, -0.1289], dtype=torch.float64)
tensor([ 1.3082, -0.4531], dtype=torch.float64)
tensor([0.9919, 0.5422], dtype=torch.float64)
tensor([-0.7798,  0.7231], dtype=torch.float64)
tensor([-0.9159,  0.1208], dtype=torch.float64)
tensor([ 1.4815, -0.2358], dtype=torch.float64)
tensor([ 0.3534, -0.0130], dtype=torch.float64)
tensor([-0.7099,  1.0695], dtype=torch.float64)
tensor([-0.5688,  0.9038], dtype=torch.float64)
tensor([ 1.3522, -0.2520], dtype=torch.float64)
tensor([-0.4210,  0.8204], dtype=torch.float64)
te

tensor([-0.6662,  0.7210], dtype=torch.float64)
tensor([ 1.2142, -0.4193], dtype=torch.float64)
tensor([ 1.3912, -0.3796], dtype=torch.float64)
tensor([0.3974, 0.8297], dtype=torch.float64)
tensor([ 1.6780, -0.4412], dtype=torch.float64)
tensor([1.8260, 0.1474], dtype=torch.float64)
tensor([0.7727, 0.6226], dtype=torch.float64)
tensor([ 1.4096, -0.3383], dtype=torch.float64)
tensor([0.0245, 0.1859], dtype=torch.float64)
tensor([ 0.5530, -0.4660], dtype=torch.float64)
tensor([ 0.4365, -0.1718], dtype=torch.float64)
tensor([ 1.5250, -0.3693], dtype=torch.float64)
tensor([ 0.8075, -0.0530], dtype=torch.float64)
tensor([-0.1563,  0.8851], dtype=torch.float64)
tensor([-0.4224,  0.9360], dtype=torch.float64)
tensor([-0.6511,  0.4897], dtype=torch.float64)
tensor([0.8041, 0.6807], dtype=torch.float64)
tensor([-0.5958,  0.6264], dtype=torch.float64)
tensor([-0.3008,  0.9185], dtype=torch.float64)
tensor([0.0623, 0.0665], dtype=torch.float64)
tensor([-1.0396,  0.3941], dtype=torch.float64)
tens

In [11]:
DataLoader(ds, batch_size=50, shuffle=True)